URLs:
- https://golang.org
- https://www.google.com
- https://www.bbc.co.uk
- https://www.github.com
- https://www.gitlab.com
- https://www.duckduckgo.com
- https://www.atlasian.com
- https://www.twitter.com
- https://www.facebook.com
MinTimeout: 10
MaxTimeout: 100
NumberOfRequests: 3